#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2026 Canonical Ltd.
#
# Guinea-pig reconstruction eval: can the onboard-workshop skill re-derive a
# real repo's workshop definition from the repo's own toolchain evidence?
#
# For each repo in GUINEA_REPOS (default: the workshop-akcano and
# vscode-workshop checkouts next to this one):
#   1. Clean-room copy: `git archive HEAD` into .work/<name>/repo (no .git,
#      no uncommitted noise).
#   2. Hide the ground truth: park .workshop/ and any root definition at
#      .work/<name>/ground-truth/; delete .workshop.lock; park CI workflow
#      files that drive the workshop CLI; redact workshop-CLI traces from
#      README.md, .gitignore, and .vscode/ metadata (string-level, structure
#      preserved). Scrubbing is approximate by design — see README.md here.
#   3. Install BOTH skills (minus tests/) into repo/.claude/skills/.
#   4. Generate .work/tests.yaml (one case per repo) and run promptfoo with
#      provider-onboard-cli.js, which runs the agent, captures generated
#      files vs ground truth, and appends the compare-definition.py scorecard.
#
# Tiers:
#   default (offline): the agent is told to STOP before launching — no LXD.
#   --tier full: the agent launches and proves actions (slow, real LXD).
#
# Requires: promptfoo, python3+yaml, claude CLI, ANTHROPIC_API_KEY (or
# _TOKEN), OPENAI_API_KEY (llm-rubric judge). Paid: ~$1-2/repo offline.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
skills_dir="$(cd "${script_dir}/../../.." && pwd)"
# Unique staging path per run: the workshop daemon keys project state by
# absolute path, so reusing a path across runs lets a previous run's
# half-launched workshop block the next launch ("stale daemon state").
# tests.yaml stays at the stable path promptfooconfig.yaml references.
work_root="${script_dir}/.work"
work="${work_root}/run-$(date -u +%Y%m%d%H%M%S)"

tier="offline"
stage_only=0
while (( $# > 0 )); do
  case "$1" in
    --tier) tier="$2"; shift 2 ;;
    --tier=*) tier="${1#--tier=}"; shift ;;
    --stage-only) stage_only=1; shift ;;
    *) echo "error: unknown argument '$1' (--tier offline|full, --stage-only)" >&2; exit 1 ;;
  esac
done
if [[ "${tier}" != "offline" && "${tier}" != "full" ]]; then
  echo "error: --tier must be 'offline' or 'full'" >&2
  exit 1
fi

default_repos="${HOME}/Documents/workshop-akcano ${HOME}/Documents/vscode-workshop"
read -r -a repos <<< "${GUINEA_REPOS:-${default_repos}}"

for cmd in promptfoo python3 claude git; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "error: '${cmd}' not found on PATH" >&2
    exit 1
  fi
done
if [[ -z "${ANTHROPIC_API_KEY:-}" && -n "${ANTHROPIC_API_TOKEN:-}" ]]; then
  export ANTHROPIC_API_KEY="${ANTHROPIC_API_TOKEN}"
fi
if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
  echo "error: set ANTHROPIC_API_KEY (or ANTHROPIC_API_TOKEN)" >&2
  exit 1
fi
if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "error: set OPENAI_API_KEY (llm-rubric judge)" >&2
  exit 2
fi

rm -rf "${work_root}"
mkdir -p "${work}"

tests_yaml="${work_root}/tests.yaml"
{
  echo "# Generated by run-reconstruction.sh — do not commit."
} > "${tests_yaml}"

staged=0
for src in "${repos[@]}"; do
  if [[ ! -d "${src}/.git" ]]; then
    echo "error: guinea-pig repo '${src}' missing or not a git checkout." >&2
    echo "       Set GUINEA_REPOS=\"/path/to/repo1 /path/to/repo2\" (like WORKSHOP_REPO for the manifest)." >&2
    exit 1
  fi
  name="$(basename "${src}")"
  sandbox="${work}/${name}"
  repo="${sandbox}/repo"
  gt="${sandbox}/ground-truth"
  mkdir -p "${repo}" "${gt}"

  echo "== Staging ${name} =="
  git -C "${src}" archive HEAD | tar -x -C "${repo}"

  # Park the ground truth.
  found_def=0
  for f in workshop.yaml .workshop.yaml; do
    if [[ -f "${repo}/${f}" ]]; then
      mv "${repo}/${f}" "${gt}/${f}"
      found_def=1
    fi
  done
  if [[ -d "${repo}/.workshop" ]]; then
    mv "${repo}/.workshop" "${gt}/.workshop"
    found_def=1
  fi
  rm -f "${repo}/.workshop.lock"
  if (( ! found_def )); then
    echo "error: ${name} has no workshop definition to reconstruct against" >&2
    exit 1
  fi

  # Park CI workflows that drive the workshop CLI (they would leak the
  # ground-truth action names), keep the rest as toolchain evidence.
  if [[ -d "${repo}/.github/workflows" ]]; then
    mkdir -p "${gt}/ci"
    while IFS= read -r wf; do
      mv "${wf}" "${gt}/ci/$(basename "${wf}")"
      echo "   parked CI workflow: $(basename "${wf}")"
    done < <(grep -lE 'launch-workshop|workshop (launch|run|exec|refresh|init|connect)' \
               "${repo}/.github/workflows/"*.y*ml 2>/dev/null || true)
  fi

  # Redact workshop-CLI traces from metadata files (structure-preserving
  # string replacement; originals parked for the record).
  mkdir -p "${gt}/redacted-originals"
  while IFS= read -r f; do
    rel="${f#"${repo}"/}"
    mkdir -p "${gt}/redacted-originals/$(dirname "${rel}")"
    cp "${f}" "${gt}/redacted-originals/${rel}"
    python3 - "$f" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p, errors="replace").read()
s = re.sub(r"workshop[ .](launch|run|exec|shell|connect|refresh|init|info|list)\b",
           "redacted", s)
s = re.sub(r"launch-workshop", "redacted", s)
s = re.sub(r"\.workshop[\w./-]*", "redacted", s)
s = re.sub(r"\bWORKSHOP\w*\b", "REDACTED", s)
if p.endswith(".json"):
    # Structure-preserving: also scrub plug/slot refs (their arguments carry
    # ground-truth workshop/SDK/plug names).
    s = re.sub(r"\b[\w-]+/[\w-]+:[\w-]+\b", "redacted", s)
else:
    # Collapse whole lines that carried CLI usage so their arguments
    # (workshop/SDK/plug names) don't leak.
    s = "\n".join(
        "redacted" if ("redacted" in ln or "REDACTED" in ln) else ln
        for ln in s.split("\n")
    )
open(p, "w").write(s)
PY
  done < <(grep -ilE 'workshop' "${repo}/README.md" "${repo}/.gitignore" \
             "${repo}/.vscodeignore" "${repo}/.vscode/"*.json 2>/dev/null || true)

  # Install both skills (minus their tests trees — also required because the
  # .work staging area lives under onboard-workshop/tests/, so a full copy
  # would recurse into itself).
  for skill in onboard-workshop use-workshop; do
    dst="${repo}/.claude/skills/${skill}"
    mkdir -p "${dst}"
    tar -C "${skills_dir}/${skill}" --exclude='./tests' -cf - . | tar -xf - -C "${dst}"
  done

  if [[ "${tier}" == "full" ]]; then
    stop_clause="Then launch the workshop and prove every generated action and tunnel per the skill's verification loop."
  else
    stop_clause="Do NOT launch the workshop or run any workshop lifecycle command other than workshop init — generate the definition files, then stop and report what you would verify."
  fi

  # Distinctive workshop name: the full tier's teardown deletes LXD
  # containers by name prefix in the user's workshop.<uid> project, so a
  # generic name like `dev` could collide with (and destroy) a real
  # workshop's container. `recon-<repo>` cannot.
  ws_name="recon-$(echo "${name}" | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-30)"
  {
    echo "- description: reconstruct ${name} (${tier})"
    echo "  vars:"
    echo "    sandbox: .work/$(basename "${work}")/${name}"
    echo "    repo_name: ${name}"
    echo "    tier: ${tier}"
    echo "    workshop_name: ${ws_name}"
    echo "    task: |"
    echo "      Onboard this repository to Workshop. It has no workshop"
    echo "      definition yet. Analyze its build/test/debug toolchain from the"
    echo "      repo's own evidence, deliver your feasibility verdict, propose"
    echo "      the definition with explicit recommendations (assume I accept"
    echo "      every recommendation), and generate it. Name the workshop"
    echo "      exactly: ${ws_name}"
    echo "      ${stop_clause}"
  } >> "${tests_yaml}"
  staged=$((staged + 1))
done

echo
if (( stage_only )); then
  echo "Staged ${staged} guinea pig(s) under ${work} (--stage-only; skipping promptfoo)"
  exit 0
fi
echo "Staged ${staged} guinea pig(s) under ${work}; running promptfoo (${tier} tier)"
cd "${script_dir}"
# Timestamped so same-day runs don't overwrite each other's raw evidence.
date_tag="$(date -u +%Y-%m-%d-%H%M%S)"
mkdir -p "${script_dir}/../results/raw"
raw_json="${script_dir}/../results/raw/${date_tag}-reconstruction-${tier}.json"

set +e
promptfoo eval -c promptfooconfig.yaml --no-cache --output "${raw_json}"
rc=$?
set -e

echo
echo "Raw results: ${raw_json}"
echo "Per-repo scorecards are embedded in each case output (--- SCORECARD ---)."
echo "Record outcomes in ../BASELINE.md (Reconstruction section)."
exit "${rc}"
