#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2026 Canonical Ltd.
#
# Regenerate tests/docs-manifest.txt and tests/allowed-keys.json from a local
# checkout of the upstream Workshop repo (canonical/workshop).
#
# This is a MAINTAINER-ONLY target — it is NOT part of `make check`, because it
# reads a repo that isn't vendored here. The two files it writes ARE committed
# and are what the offline CI guards (check-source-docs.sh, check-yaml-keys.py)
# validate against. Rerun this when bumping the skill to a new Workshop version,
# then review and commit the diff.
#
# Usage:
#   WORKSHOP_REPO=~/Documents/workshop-akcano \
#     make -C .github/skills/use-workshop/tests update-docs-manifest
#
# WORKSHOP_REPO must point at a checkout whose docs/ tree is the doc source for
# the version the skill now targets (typically main at the relevant commit).

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tests_dir="$(cd "${script_dir}/.." && pwd)"

if [[ -z "${WORKSHOP_REPO:-}" ]]; then
  echo "error: set WORKSHOP_REPO to a local Workshop checkout, e.g." >&2
  echo "  WORKSHOP_REPO=~/Documents/workshop-akcano make update-docs-manifest" >&2
  exit 2
fi

repo="${WORKSHOP_REPO/#\~/$HOME}"
docs="${repo}/docs"
if [[ ! -d "${docs}" ]]; then
  echo "error: no docs/ directory under WORKSHOP_REPO=${repo}" >&2
  exit 2
fi

sha="$(git -C "${repo}" rev-parse --short HEAD 2>/dev/null || echo unknown)"

manifest="${tests_dir}/docs-manifest.txt"
keys="${tests_dir}/allowed-keys.json"

WORKSHOP_DOCS="${docs}" WORKSHOP_SHA="${sha}" \
  MANIFEST_OUT="${manifest}" KEYS_OUT="${keys}" \
  python3 - <<'PY'
import json, os, re

docs = os.environ["WORKSHOP_DOCS"]
sha = os.environ["WORKSHOP_SHA"]

# --- docs-manifest.txt -------------------------------------------------------
# Every reader-facing doc page, as a path relative to the docs base, with the
# .md extension the rendered site (and the skill's <source_docs>) use. RST
# sources render to .md; authored .md sources are kept as-is. Excluded: the
# Sphinx venv, the built mirror, include-only fragment dirs (any path segment
# starting with "_"), the 404/readme stubs, and every per-subcommand CLI page
# (the CLI reference renders as four combined pages, one per tool).
allowed_cli = re.compile(r"^(workshop|sdk|sdkcraft|workshopctl)\.md$")
paths = set()
for root, dirs, files in os.walk(docs):
    dirs[:] = [d for d in dirs if d not in (".venv", "_build") and not d.startswith("_")]
    for fn in files:
        rel = os.path.relpath(os.path.join(root, fn), docs)
        if any(seg.startswith("_") for seg in rel.split(os.sep)):
            continue
        if fn.endswith(".rst"):
            md = rel[:-4] + ".md"
        elif fn.endswith(".md"):
            md = rel
        else:
            continue
        base = os.path.basename(md)
        if base in ("404.md", "readme.md"):
            continue
        if rel.startswith("reference/cli/") and not allowed_cli.match(base):
            continue
        paths.add(md.replace(os.sep, "/"))
paths.add("llms.txt")
for schema in ("schema", "schema-sdk", "schema-sdkcraft"):
    paths.add(f"reference/definition-files/{schema}.json")

# Build the SPDX tag from a variable so this generator's own source file does
# not contain a second, bare "<tag>: GPL-3.0-only" line that REUSE would try to
# parse as a license expression.
spdx = "SPDX-License-" + "Identifier"
with open(os.environ["MANIFEST_OUT"], "w") as fh:
    fh.write(f"# {spdx}: GPL-3.0-only\n")
    fh.write("# Copyright 2026 Canonical Ltd.\n")
    fh.write("#\n")
    fh.write(f"# Generated by scripts/update-docs-manifest.sh from canonical/workshop @ {sha}.\n")
    fh.write("# Do not edit by hand. Reader-facing doc pages, relative to the docs base.\n")
    fh.write("# check-source-docs.sh validates every <source_docs> path against this list.\n")
    for p in sorted(paths):
        fh.write(p + "\n")

# --- allowed-keys.json -------------------------------------------------------
# Top-level keys accepted in each user-authored YAML shape, read straight from
# the upstream JSON schemas. check-yaml-keys.py lints the skill's YAML snippets
# against these. Note the sdk schema has NO `hooks` key — that omission is the
# guard against reintroducing a `hooks:` field in an in-project sdk.yaml.
def top_props(name):
    with open(os.path.join(docs, "reference", "definition-files", name)) as fh:
        return sorted(json.load(fh).get("properties", {}).keys())

allowed = {
    "_comment": f"Generated by scripts/update-docs-manifest.sh from canonical/workshop @ {sha}. Do not edit by hand.",
    "workshop": top_props("schema.json"),
    "sdk": top_props("schema-sdk.json"),
    "sdkcraft": top_props("schema-sdkcraft.json"),
}
with open(os.environ["KEYS_OUT"], "w") as fh:
    json.dump(allowed, fh, indent=2)
    fh.write("\n")

print(f"Wrote {os.environ['MANIFEST_OUT']} ({len(paths)} paths)")
print(f"Wrote {os.environ['KEYS_OUT']} (workshop/sdk/sdkcraft key allowlists)")
PY

echo "ok: regenerated from canonical/workshop @ ${sha}"
